### ISSUE TITLE
Missing Colours

### ISSUE THREAD

**Issue by theFroh** [golf1052/base16-generator#1]
Hey -- great work with this! Definitely will be my go-to for themeing.
I just noticed some odd highlighting behaviours, I believe due to a missing colour or similar:

This is using a separate Gruvbox theme.
![image](https://user-images.githubusercontent.com/2473822/28706130-7c030704-73a5-11e7-9519-98e85f4c2f0e.png)

Compare to a generated base16-spacemacs-dark:
![image](https://user-images.githubusercontent.com/2473822/28706183-b2e00ce0-73a5-11e7-9b3b-792cfdb5b2ec.png)

Or generated base16-gruvbox:
![image](https://user-images.githubusercontent.com/2473822/28706222-e0cce574-73a5-11e7-85b0-b20bdfb95080.png)

Rather odd! If I get a chance, I'll dig into the theme formats for VS Code to see if I can't uncover this myself.

**Comment by golf1052** [comment]
OK I've made some updates.

![](http://i.imgur.com/6Jj2VNQ.png)
![](http://i.imgur.com/wm01SSt.png)

According to the base16 spec (http://chriskempson.com/projects/base16/) keywords should be base0E (purple). I've changed it so that if is now marked correctly as a keyword.

This change has been pushed in v1.1.0
