### ISSUE TITLE
The move to base16-project GitHub organization

### ISSUE THREAD

**Issue by JamyGolden** [golf1052/base16-generator#30]
Hi @golf1052, there is a group of us working on [reviving the base16 project](https://github.com/base16-project) and I'm wondering if you'd be willing to join?

The [discussion about a base16 Github organization](https://github.com/chriskempson/base16/issues/74) initially started in 2016. Now, with the disappearance of Chris Kempson, the importance of the [base16](https://github.com/base16-project/base16) organization is more vital than ever to keep the project structured and thriving. Currently there is a "deprecation" notice on the old [chriskempson/base16](https://github.com/chriskempson/base16) repo.

Seeing as you maintain this repo (and other base16 repos), we're [looking for more colaborators](https://github.com/base16-project/base16/issues/2) and I was wondering if you are you interested in joining [github.com/base16-project](https://github.com/base16-project) and helping us maintain some of the projects?

Right now, logistical communication around this is happening at https://github.com/base16-project/base16/issues/1. Some of us are also on #base16 on Libera Chat [IRC] (for more general discussions and hangouts)

Are you interested in maintaining any [base16-project](https://github.com/base16-project) repositories and being part of the organization?

**Comment by golf1052** [comment]
It looks like the original base16 project doesn't have a deprecation notice anymore but I think it's good the base16-project org exists now. When I started updating this repo in the last few days read through some of your repos and issues. I'd be glad to join the org as a collaborator but my focus has always been on just (poorly as you can see by the large gap since the last update) maintaining a decently high quality VSCode extension that supports all the known base16 themes (and the [underlying builder that is required](https://github.com/golf1052/base16-builder-typescript)). I wouldn't want to be responsible for updating other builders or schemes besides the ones I currently maintain.

I'm also somewhat skeptical of base24 as I'd assume the plan would be to update all known base16 schemes to support base24 which seems like a somewhat large undertaking if you want scheme authors to update their schemes.

**Comment by JamyGolden** [comment]
Yes there was a lot that changed soon after I sent you the message which, I'm guessing you've come across, is summarised here: https://github.com/base16-project/home/issues/51.Yes I totally understand joining and only maintaining this project. The goal isn't to have maintainers update all their templates to support base24, the builders will be backwards compatible and it will allow template maintainers to fix existing bugs (https://github.com/base16-project/home/issues/10). It's not a feature, not a requirement though.

I'll add you to the org and you should be able to transfer the project under the repo settings page.

**Comment by golf1052** [comment]
I've transferred in the [base16-vscode](https://github.com/base16-project/base16-vscode) project. I would need to figure out which contributors I'd need to add to the npm project for [base16-builder-typescript](https://www.npmjs.com/package/base16-builder-typescript). I'd like to keep this repo under my account for the time being but the latter items can be discussed in the org.
