### ISSUE TITLE
GitHub theme uses VS Code's Dark settings

### ISSUE THREAD

**Issue by chriskrycho** [golf1052/base16-generator#4]
It's hard to show this via a screenshot b/c of the way macOS captures screenshots, but the cursor is definitely the cursor for dark modes, and tabs are separated by dark lines instead of a light gray. Seems like it's just using the wrong VS Code option there.

It's [here](https://github.com/golf1052/base16-generator/blob/da232a774206ff4610c60f31cc580cbd2a14a846/themes/base16-github.json#L3).

**Comment by golf1052** [comment]
Thanks for the report. Just switching the `type` from dark to light in the theme isn't fully correct as I generate the themes using a few scripts (see [contributing](https://github.com/golf1052/base16-generator/blob/master/CONTRIBUTING.md)).

The best way to fix this is to update the script ([finish-themes.ts](https://github.com/golf1052/base16-generator/blob/master/src/scripts/finish-themes.ts)) that updates the JSON theme file with the type info. [Right now it just checks the file name](https://github.com/golf1052/base16-generator/blob/master/src/scripts/finish-themes.ts#L18). That doesn't work in all cases, like this one, if there is no info about the theme type in the file name.

Since it's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) I'll leave this open if you're interested in fixing the script.

My proposed fix is to take the same [isColorDark](https://github.com/golf1052/base16-generator/blob/master/src/scripts/generate-light-schemes.ts#L262-L266) function and use that to check if the JSON theme is light or dark. It's probably best to check if `base00` is light or dark so check `editor.background` in the JSON theme. Then use that info to set `type` appropriately.

**Comment by chriskrycho** [comment]
Ah, I see. Neat. I don't need the PR for Hacktoberfest, and I'm [swamped](https://github.com/typed-ember/ember-cli-typescript) with [other projects](https://github.com/typed-ember/ember-typings) so if you end up having time, go for it.

Also: 🤦‍♂️ sorry I forgot to read the Contributing doc.

**Comment by golf1052** [comment]
Just pushed 1.3.0 that fixes this. Thanks for another report and using my extension!
